### ISSUE TITLE
NEW FEATURE: Fire webhooks on stop/start

### ISSUE THREAD

**Issue by troylar** [kevinschoon/pomo#10]

**Comment by kevinschoon** [comment]
Thanks for the suggestion @troylar, that should be pretty easy to implement.
Won't be able to get to it immediately but will definitely keep it in mind for future releases, PR's are also always welcome!

**Comment by kevinschoon** [comment]
This should now be possible since merging https://github.com/kevinschoon/pomo/pull/61
