### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ElModdy** [kevinschoon/pomo#12]
Hi, where can I find a complete documentation?

**Comment by kevinschoon** [comment]
Hi @ElModdy , the only documentation is available in the README or on the project website https://kevinschoon.github.io/pomo/. If you're looking for something in particular please ask here and we'll add it to the README.

**Comment by CyrilAntoni** [comment]
Hi @kevinschoon,
Thank you for the great CLI!

I'm looking for a complete list of the options that can be used with `pomo`. For example the GIF on top of the README presents the `--tag`, `--duration` and `--pomodoros` options that are not yet documented in the README file nor in the `pomo -h` documentation.
![image](https://user-images.githubusercontent.com/13135150/64946559-72c71880-d873-11e9-9079-6598ebc6ced1.png)

Cordially,
Cyril

**Comment by CyrilAntoni** [comment]
Alright, never mind!
Turns out the `pomo COMMAND --help` is the way to go to get all the documentation needed!
Maybe mentioning it somewhere in the documentation would be helpful to beginners like me.
