### ISSUE TITLE
Unable to quit with accidental [enter] after completion

### ISSUE THREAD

**Issue by binshengliu** [kevinschoon/pomo#15]
If `[enter]` is accidentally pressed after completion, the program doesn't quit and can only be killed.

Can we allow `[enter]` to quit at completion?

```
$ pomo -v
0.7.1
```

**Comment by kevinschoon** [comment]
Thanks for reporting this @binshengliu, I don't have an ETA currently but will get it fixed in the next release.

**Comment by kevinschoon** [comment]
Added a fix for this in https://github.com/kevinschoon/pomo/commit/1b321198fbc47216065616301e0cbd30e193b44d
