### ISSUE TITLE
FYI: sqlite3 runtime is not required

### ISSUE THREAD

**Issue by mattn** [kevinschoon/pomo#2]
go-sqlite3 is built as static-linked. So if you compile pomo without tag `-tags libsqlite3`, it works without sqlite3 runtime.

**Comment by kevinschoon** [comment]
@mattn Thank you for the tip! I realize now that sqlite3 is not needed at all because you link against the [amalgamated](https://www.sqlite.org/amalgamation.html) lib by default.
