### ISSUE TITLE
[Question] A way to resume tasks

### ISSUE THREAD

**Issue by Revanee** [kevinschoon/pomo#24]
Is there a way to start an existing task? Maybe by ID given from `list`

**Comment by aThorp96** [comment]
`pomo begin <ID>` seems to resume a task for me

**Comment by kevinschoon** [comment]
@aThorp96 is correct, once a task has been stopped it can be resumed with `pomo begin <ID>`.

**Comment by strogiyotec** [comment]
@Revanee  could you close the ticket if it helped you

**Comment by Revanee** [comment]
Yeah, apparently the version in the aur is outdated and still doesn't have the command
