### ISSUE TITLE
Pressing `p` from the break screen breaks things

### ISSUE THREAD

**Issue by aThorp96** [kevinschoon/pomo#25]
Accidentally pressing `p` from the break screen seems to cause some sort of lock to occur. The UI accepts no input or interrupts and I've only been able to kill it by closing the tmux pane pomo is running in. I haven't dug in too deep, but I think this might be fixable by adding some checks to TaskRunner.Pause().

**Comment by aThorp96** [comment]
An alternative, and perhaps less computationally expensive, fix for this would be to refactor runner to run using a state machine and have the run loop operate off of sentinel values sent through a single channel of ints

**Comment by aThorp96** [comment]
Just realized the runner is being redesigned in the develop branch. I did confirm develop currently has the same bug though.

**Comment by kevinschoon** [comment]
@aThorp96 I agree about the state machine, will leave this open and address it in the next release.

**Comment by strogiyotec** [comment]
@kevinschoon  are you working on it right now ? I have the same problem now , could fix it in free time

**Comment by Poroing** [comment]
Is anyone working on this issue ? I could try to learn GO and fix this.

**Comment by kevinschoon** [comment]
Added a fix for this in https://github.com/kevinschoon/pomo/commit/1b321198fbc47216065616301e0cbd30e193b44d
