### ISSUE TITLE
How to: Add to Path

### ISSUE THREAD

**Issue by javag97** [kevinschoon/pomo#43]
`install.sh` states:

```bash
Pomo 0.7.1 installed, copy ./pomo to somewhere on your path.
```

I tried to add it, but didn't work. I even created ./pomo and put binary file in that directory, but no luck.

**Comment by gerdm** [comment]
Have you modified your path? For example, I did the following:

```
export PATH="/Users/gerardoduran/pomo:$PATH"
```

where `pomo` is a directory I created with the `pomo` file.
