### ISSUE TITLE
System tray notification/icon

### ISSUE THREAD

**Issue by kasisnu** [kevinschoon/pomo#8]
Is this currently wip? If not, I'd like to volunteer to try to do this on osx.

**Comment by kevinschoon** [comment]
@kasisnu We implemented cross-platform support in https://github.com/kevinschoon/pomo/pull/3. It works without issue for me on Linux however I haven't really tested personally on OSX or Windows. If it's not working out of the box for you then it's a bug. @JackMordaunt did some work on this last year so maybe he can confirm.

**Comment by kasisnu** [comment]
Hi @kevinschoon. Not sure how I missed it but it's working fine for me on OSX(mojave). Thanks. 👍
