### ISSUE TITLE
GLIBC_2.28 not found

### ISSUE THREAD

**Issue by benjamin-thomas** [kevinschoon/pomo#9]
OS=Ubuntu 16.04.5 LTS
Kernel=4.4.0-141-generic

---

Hello,

The dynamically linked binary release generates the following error on my system:

    ./pomo: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./pomo)

After googling around, I installed the following package 

    apt-get install libc6

With no changes. It I'm not sure how libc is managed by default on Ubuntu since that package did install, however I cannot remove it anymore (other binaries depend on it).

Here is the `file` command output against the binary:

    pomo: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=49487bb8d010bb7dfa52de73c04974c1e50b820e, not stripped

**Comment by benjamin-thomas** [comment]
Release=Pomo 0.7.0 btw

**Comment by kevinschoon** [comment]
Thanks for reporting the issue @benjamin-thomas, must be related to the `0.7.0` release I made recently, I will test on Ubuntu over the weekend.

**Comment by kevinschoon** [comment]
Hey @benjamin-thomas -- I was compiling against a newer version of libc locally which was causing the issues. I updated the build environment to compile against a Debian container by default and the new binaries no longer produce the error you reported.

You can download a new binary from my last release https://github.com/kevinschoon/pomo/releases/tag/0.7.1 or just re-run the installer script.

Thanks!
